### ISSUE TITLE
Update zeekoe demo

### ISSUE THREAD

**Issue by DariusParvin** [boltlabs-inc/zeekoe#193]
Update zeekoe demo to:
- work with the latest version of the contract (after changes introduced in #37)
- work with a sandbox node

**Comment by marsella** [comment]
@DariusParvin Is this issue still live? The listed items have already been taken care of. Are there other specific things that need to be updated?

**Comment by DariusParvin** [comment]
I think this issue is outdated. It was when we used a different python script to help with broadcasting operations on chain. Now that zeekoe itself takes care of everything, the demo is what is described in the zeekoe readme.
