### ISSUE TITLE
Update transport module to be public

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/zeekoe#366]
We want to reuse the zeekoe transport module in the key-mgmt product, but it's currently private.

Easiest solution: make it a public module within zeekoe.
Another option: make it its own crate.

In either case, browse through the module before just making it public to be sure that the public interface is appropriately scoped.

**Comment by indomitableSwan** [comment]
I would advocate for modularity, i.e., splitting out any zeekoe logic we want to use into its own crate.

**Comment by marsella** [comment]
I think this is closed with #366 and the creation of [the transport crate](https://github.com/boltlabs-inc/transport). Can re-open if we realize this isn't complete.
